//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auditory_type")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auditory_type_to_auditory::Entity")]
    AuditoryTypeToAuditory,
}

impl Related<super::auditory_type_to_auditory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditoryTypeToAuditory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
