//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auditory_type_to_auditory")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub auditory_id: i32,
    pub auditory_type_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auditory::Entity",
        from = "Column::AuditoryId",
        to = "super::auditory::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Auditory,
    #[sea_orm(
        belongs_to = "super::auditory_type::Entity",
        from = "Column::AuditoryTypeId",
        to = "super::auditory_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AuditoryType,
}

impl Related<super::auditory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auditory.def()
    }
}

impl Related<super::auditory_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditoryType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
