//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "direction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub full_name: String,
    pub short_name: String,
    pub faculty_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::faculty::Entity",
        from = "Column::FacultyId",
        to = "super::faculty::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Faculty,
    #[sea_orm(has_many = "super::group::Entity")]
    Group,
    #[sea_orm(has_many = "super::speciality::Entity")]
    Speciality,
}

impl Related<super::faculty::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Faculty.def()
    }
}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Group.def()
    }
}

impl Related<super::speciality::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Speciality.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
