//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub number_pair: i16,
    pub r#type: String,
    pub subject_id: i32,
    pub auditory_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auditory::Entity",
        from = "Column::AuditoryId",
        to = "super::auditory::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Auditory,
    #[sea_orm(has_many = "super::event_to_group::Entity")]
    EventToGroup,
    #[sea_orm(has_many = "super::event_to_teacher::Entity")]
    EventToTeacher,
    #[sea_orm(
        belongs_to = "super::subject::Entity",
        from = "Column::SubjectId",
        to = "super::subject::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Subject,
}

impl Related<super::auditory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auditory.def()
    }
}

impl Related<super::event_to_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventToGroup.def()
    }
}

impl Related<super::event_to_teacher::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventToTeacher.def()
    }
}

impl Related<super::subject::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subject.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
