//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "faculty")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub full_name: String,
    pub short_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::department::Entity")]
    Department,
    #[sea_orm(has_many = "super::direction::Entity")]
    Direction,
}

impl Related<super::department::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Department.def()
    }
}

impl Related<super::direction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Direction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
