//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub mod prelude;

pub mod auditory;
pub mod auditory_type;
pub mod auditory_type_to_auditory;
pub mod building;
pub mod department;
pub mod direction;
pub mod event;
pub mod event_to_group;
pub mod event_to_teacher;
pub mod faculty;
pub mod group;
pub mod speciality;
pub mod subject;
pub mod subject_to_teacher;
pub mod teacher;
