//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::auditory::Entity as Auditory;
pub use super::auditory_type::Entity as AuditoryType;
pub use super::auditory_type_to_auditory::Entity as AuditoryTypeToAuditory;
pub use super::building::Entity as Building;
pub use super::department::Entity as Department;
pub use super::direction::Entity as Direction;
pub use super::event::Entity as Event;
pub use super::event_to_group::Entity as EventToGroup;
pub use super::event_to_teacher::Entity as EventToTeacher;
pub use super::faculty::Entity as Faculty;
pub use super::group::Entity as Group;
pub use super::speciality::Entity as Speciality;
pub use super::subject::Entity as Subject;
pub use super::subject_to_teacher::Entity as SubjectToTeacher;
pub use super::teacher::Entity as Teacher;
