services:
  postgres:
    image: postgres:latest
    container_name: schedule_postgres_container
    restart: always
    environment:
      POSTGRES_USER: schedule
      POSTGRES_PASSWORD: schedule_pass
      POSTGRES_DB: schedule
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: schedule_pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
