services:
  mariadb:
    image: mariadb:latest
    container_name: schedule_mariadb_container
    restart: no
    environment:
      MARIADB_USER: schedule
      MARIADB_PASSWORD: schedule_pass
      MARIADB_ROOT_PASSWORD: root_pass
      MARIADB_DATABASE: schedule
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - schedule_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: schedule_phpmyadmin_container
    restart: no
    environment:
      PMA_HOST: mariadb
      PMA_USER: schedule
      PMA_PASSWORD: schedule_pass
    ports:
      - "8080:80"
    networks:
      - schedule_network

networks:
  schedule_network:

volumes:
  mariadb_data:
